#!/bin/bash
set -e

# Create prod/staging env files for backup-restore sync
# Usage: sudo bash odoo-sync-env-create.sh <suffix> [--prod-instance name] [--staging-instance name] [--with-sync-env] [--force]

usage() {
    cat <<EOF
Usage: $0 <suffix> [--prod-instance name] [--staging-instance name] [--with-sync-env] [--force]

Examples:
  sudo $0 19
  sudo $0 19 --prod-instance prod19 --staging-instance staging19
  sudo $0 19 --with-sync-env
EOF
}

SUFFIX="$1"
if [ -z "$SUFFIX" ]; then
    usage
    exit 1
fi
shift

PROD_INSTANCE="prod${SUFFIX}"
STAGING_INSTANCE="staging${SUFFIX}"
WITH_SYNC_ENV="false"
FORCE="false"

while [[ "$#" -gt 0 ]]; do
    case "$1" in
        --prod-instance) PROD_INSTANCE="$2"; shift ;;
        --staging-instance) STAGING_INSTANCE="$2"; shift ;;
        --with-sync-env) WITH_SYNC_ENV="true" ;;
        --force) FORCE="true" ;;
        *) echo "Unknown argument: $1"; exit 1 ;;
    esac
    shift
done

ENV_DIR="/etc/odoo_deploy"
PROD_ENV="${ENV_DIR}/prod${SUFFIX}.env"
STAGING_ENV="${ENV_DIR}/staging${SUFFIX}.env"

write_env() {
    local instance="$1"
    local target="$2"
    local target_name="$3"

    local src="${ENV_DIR}/${instance}.env"
    if [ ! -f "$src" ]; then
        echo "❌ Missing source env: $src"
        exit 1
    fi

    # shellcheck disable=SC1090
    source "$src"

    if [ -z "$OE_HOME" ] || [ -z "$OE_USER" ] || [ -z "$DB_NAME" ]; then
        echo "❌ $src missing required fields (OE_HOME, OE_USER, DB_NAME)"
        exit 1
    fi

    if [ -f "$target" ] && [ "$FORCE" != "true" ]; then
        echo "⚠ $target already exists (use --force to overwrite)"
        return 0
    fi

    cat <<EOF >"$target"
# Auto-generated by odoo-sync-env-create.sh
INSTANCE_NAME=$target_name
OE_HOME=$OE_HOME
OE_USER=$OE_USER
SERVICE_NAME=${SERVICE_NAME:-odoo}
BRANCH=$BRANCH
DB_NAME=$DB_NAME
DB_USER=${DB_USER:-$OE_USER}
DB_HOST=${DB_HOST:-localhost}
DB_PORT=${DB_PORT:-5432}
ODOO_PORT=${ODOO_PORT:-8069}
EOF
    chmod 640 "$target"
    echo "✓ Wrote $target"
}

mkdir -p "$ENV_DIR"

write_env "$PROD_INSTANCE" "$PROD_ENV" "prod${SUFFIX}"
write_env "$STAGING_INSTANCE" "$STAGING_ENV" "staging${SUFFIX}"

if [ "$WITH_SYNC_ENV" = "true" ]; then
    SYNC_ENV="${ENV_DIR}/odoo-sync.env"
    if [ -f "$SYNC_ENV" ] && [ "$FORCE" != "true" ]; then
        echo "⚠ $SYNC_ENV already exists (use --force to overwrite)"
        exit 0
    fi
    cat <<EOF >"$SYNC_ENV"
# Optional defaults for odoo-sync.sh
PROD_SSH_USER=root
# PROD_MASTER_PASS=your_master_password
# STAGING_MASTER_PASS=your_master_password

# BACKUP_METHOD=pg        # pg | odoo | auto
# RESTORE_METHOD=pg       # pg | odoo
# DROP_METHOD=auto        # auto | odoo | pg
# NO_FILESTORE=false
EOF
    chmod 640 "$SYNC_ENV"
    echo "✓ Wrote $SYNC_ENV"
fi
